require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/productModel');

const CAT = {
  electronics:  '6a476f70f11db8f264c062d7',
  fashionMen:   '6a476f70f11db8f264c062d8',
  fashionWomen: '6a476f70f11db8f264c062d9',
  home:         '6a476f70f11db8f264c062da',
  books:        '6a476f70f11db8f264c062db',
  health:       '6a476f70f11db8f264c062dc',
  sports:       '6a476f70f11db8f264c062dd',
  gaming:       '6a476f70f11db8f264c062de',
};

// Each image URL points to a real, category-accurate photo
const products = [

  // ───────────────────────────── ELECTRONICS ─────────────────────────────
  {
    name: 'Sony WH-1000XM5 Noise Cancelling Headphones',
    description: 'Industry-leading noise cancellation with Dual Noise Sensor technology. 30-hour battery, quick charge, crystal-clear hands-free calling.',
    price: 24999, compareAtPrice: 34990, stock: 18, ratings: 4.9, numOfReviews: 342,
    category: CAT.electronics, sku: 'SONY-WH1000XM5',
    tags: ['electronics','audio','wireless','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', public_id: 'p1' }],
  },
  {
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    description: 'A17 Pro chip, titanium design, 48MP main camera with 5x optical zoom, USB-C connectivity, and Action Button. The most advanced iPhone ever.',
    price: 134900, compareAtPrice: 149900, stock: 12, ratings: 4.9, numOfReviews: 512,
    category: CAT.electronics, sku: 'APPLE-IP15PM-256',
    tags: ['electronics','smartphone','apple','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80', public_id: 'p2' }],
  },
  {
    name: 'Samsung Galaxy S24 Ultra 512GB Titanium Black',
    description: 'Galaxy AI, 200MP ProVisual Camera, integrated S Pen, 12GB RAM, 5000mAh battery. Built for power users.',
    price: 129999, compareAtPrice: 149999, stock: 9, ratings: 4.8, numOfReviews: 298,
    category: CAT.electronics, sku: 'SAM-S24U-512',
    tags: ['electronics','smartphone','samsung'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80', public_id: 'p3' }],
  },
  {
    name: 'Apple MacBook Air M3 13" 8GB/256GB Midnight',
    description: 'Supercharged by M3 chip. Up to 18-hour battery life, 13.6" Liquid Retina display, fanless silent design, 1080p FaceTime camera.',
    price: 114900, compareAtPrice: 124900, stock: 7, ratings: 4.9, numOfReviews: 187,
    category: CAT.electronics, sku: 'APPLE-MBA-M3-8-256',
    tags: ['electronics','laptop','apple','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1611186871525-405de2a3e21c?w=600&q=80', public_id: 'p4' }],
  },
  {
    name: 'Dell XPS 15 OLED Intel i7 13th Gen 16GB/512GB',
    description: '15.6" OLED touch display, Intel Core i7-13700H, NVIDIA RTX 4060, 16GB DDR5, 512GB SSD. Creator-grade performance in a premium chassis.',
    price: 142999, compareAtPrice: 159999, stock: 5, ratings: 4.7, numOfReviews: 134,
    category: CAT.electronics, sku: 'DELL-XPS15-OLED',
    tags: ['electronics','laptop','dell'], isTrending: false,
    images: [{ url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&q=80', public_id: 'p5' }],
  },
  {
    name: 'iPad Air M2 11" 128GB Wi-Fi Space Grey',
    description: 'Apple M2 chip, 11-inch Liquid Retina display, USB-C, 5G capable (Wi-Fi model), Apple Pencil and Magic Keyboard compatible.',
    price: 69900, compareAtPrice: 79900, stock: 14, ratings: 4.8, numOfReviews: 203,
    category: CAT.electronics, sku: 'APPLE-IPADAIR-M2-128',
    tags: ['electronics','tablet','apple'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80', public_id: 'p6' }],
  },
  {
    name: 'Sony Alpha A7 IV Full-Frame Mirrorless Camera Body',
    description: '33MP BSI CMOS sensor, 4K 60fps video, 10fps continuous shooting, real-time tracking AF, weather-sealed magnesium body.',
    price: 249990, compareAtPrice: 279990, stock: 4, ratings: 4.9, numOfReviews: 89,
    category: CAT.electronics, sku: 'SONY-A7IV-BODY',
    tags: ['electronics','camera','photography'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80', public_id: 'p7' }],
  },
  {
    name: 'Samsung 65" 4K Neo QLED Smart TV QN65QN85C',
    description: 'Neo QLED, 4K AI Upscaling Pro, Quantum HDR, Object Tracking Sound+, Gaming Hub, 144Hz for PC and console gaming.',
    price: 149999, compareAtPrice: 189999, stock: 6, ratings: 4.8, numOfReviews: 156,
    category: CAT.electronics, sku: 'SAM-NEOQLED-65',
    tags: ['electronics','tv','samsung'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=600&q=80', public_id: 'p8' }],
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm Starlight Aluminium',
    description: 'S9 SiP chip, Double Tap gesture, Always-On Retina display, crash detection, ECG app, blood oxygen sensor, 18-hour battery.',
    price: 44900, compareAtPrice: 49900, stock: 20, ratings: 4.8, numOfReviews: 289,
    category: CAT.electronics, sku: 'APPLE-AW9-45MM',
    tags: ['electronics','smartwatch','apple','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80', public_id: 'p9' }],
  },
  {
    name: 'Bose QuietComfort 45 Wireless Headphones White Smoke',
    description: 'Proprietary acoustic noise-cancelling technology, TriPort acoustic structure, up to 24-hour battery, foldable design with carrying case.',
    price: 21999, compareAtPrice: 28999, stock: 15, ratings: 4.7, numOfReviews: 198,
    category: CAT.electronics, sku: 'BOSE-QC45-WS',
    tags: ['electronics','audio','wireless'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80', public_id: 'p10' }],
  },
  {
    name: 'DJI Mini 4 Pro Drone Fly More Combo',
    description: '4K/60fps HDR video, 48MP photos, obstacle sensing in all directions, 34-min flight time, 20km transmission range. Under 249g.',
    price: 89900, compareAtPrice: 99900, stock: 8, ratings: 4.9, numOfReviews: 112,
    category: CAT.electronics, sku: 'DJI-MINI4PRO-FMC',
    tags: ['electronics','drone','photography','trending'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&q=80', public_id: 'p11' }],
  },
  {
    name: 'OnePlus 12 5G 16GB/512GB Flowy Emerald',
    description: 'Snapdragon 8 Gen 3, Hasselblad triple camera, 50W wireless charging, 5400mAh battery, 120Hz 2K LTPO AMOLED display.',
    price: 64999, compareAtPrice: 74999, stock: 22, ratings: 4.7, numOfReviews: 245,
    category: CAT.electronics, sku: 'OP12-512-GRN',
    tags: ['electronics','smartphone','oneplus'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80', public_id: 'p12' }],
  },
  {
    name: 'Logitech MX Master 3S Wireless Mouse Graphite',
    description: '8K DPI sensor, ultra-fast MagSpeed scroll wheel, USB-C charging, 70-day battery, works on any surface including glass.',
    price: 9995, compareAtPrice: 11995, stock: 35, ratings: 4.9, numOfReviews: 432,
    category: CAT.electronics, sku: 'LOGI-MXM3S-GR',
    tags: ['electronics','peripherals','mouse'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80', public_id: 'p13' }],
  },
  {
    name: 'Anker 737 Power Bank 140W 24000mAh',
    description: '140W fast charging, powers laptops, 24000mAh capacity, charges iPhone 15 3 times, smart display, bidirectional charging.',
    price: 11999, compareAtPrice: 14999, stock: 28, ratings: 4.7, numOfReviews: 178,
    category: CAT.electronics, sku: 'ANKER-737-PB',
    tags: ['electronics','accessories','charging'],
    images: [{ url: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', public_id: 'p14' }],
  },
  {
    name: 'JBL Charge 5 Portable Bluetooth Speaker Black',
    description: '20-hour playtime, IP67 waterproof and dustproof, PartyBoost to pair multiple speakers, USB-A charging out for devices.',
    price: 14999, compareAtPrice: 19999, stock: 24, ratings: 4.8, numOfReviews: 312,
    category: CAT.electronics, sku: 'JBL-CHG5-BLK',
    tags: ['electronics','audio','bluetooth'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80', public_id: 'p15' }],
  },

  // ───────────────────────────── FASHION MEN ─────────────────────────────
  {
    name: "Levi's 511 Slim Fit Stretch Jeans Dark Indigo",
    description: `Slim fit through thigh and leg, stretch fabric for all-day comfort, authentic 5-pocket styling, sits below waist.`,
    price: 4499, compareAtPrice: 5999, stock: 50, ratings: 4.6, numOfReviews: 234,
    category: CAT.fashionMen, sku: 'LEVIS-511-DI-32',
    tags: ['fashion','men','jeans','casual'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80', public_id: 'p16' }],
  },
  {
    name: "Allen Solly Men's Regular Fit Formal Shirt White",
    description: `100% cotton premium formal shirt, regular fit, spread collar, button-down front, wrinkle-resistant fabric, machine washable.`,
    price: 1299, compareAtPrice: 1999, stock: 80, ratings: 4.4, numOfReviews: 156,
    category: CAT.fashionMen, sku: 'AS-FORMAL-WHT-M',
    tags: ['fashion','men','formal','shirt'],
    images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80', public_id: 'p17' }],
  },
  {
    name: 'Peter England Men Navy Blue Suit Three-Piece',
    description: `Premium wool-blend three-piece suit: jacket, trousers, and waistcoat. Slim fit silhouette, half-canvas construction, peak lapels.`,
    price: 8999, compareAtPrice: 13999, stock: 20, ratings: 4.7, numOfReviews: 89,
    category: CAT.fashionMen, sku: 'PE-SUIT-NAVY-42',
    tags: ['fashion','men','formal','suit'],
    images: [{ url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80', public_id: 'p18' }],
  },
  {
    name: 'Nike Air Force 1 Low White Sneakers',
    description: `Iconic low-top silhouette with genuine leather upper, encapsulated Air cushioning, herringbone-pattern rubber outsole.`,
    price: 7495, compareAtPrice: 8995, stock: 40, ratings: 4.8, numOfReviews: 520,
    category: CAT.fashionMen, sku: 'NIKE-AF1-WHT-10',
    tags: ['fashion','men','shoes','sneakers','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', public_id: 'p19' }],
  },
  {
    name: "Wrangler Men's Regular Fit Cargo Pants Olive",
    description: `Relaxed seat and thigh with straight leg opening, multiple utility pockets, durable ripstop fabric, reinforced stress points.`,
    price: 1799, compareAtPrice: 2499, stock: 60, ratings: 4.3, numOfReviews: 142,
    category: CAT.fashionMen, sku: 'WRANGLER-CARGO-OLV-32',
    tags: ['fashion','men','cargo','casual'],
    images: [{ url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80', public_id: 'p20' }],
  },
  {
    name: 'Tommy Hilfiger Men Classic Polo Shirt Navy',
    description: `Signature Tommy Hilfiger polo with piqué fabric, embroidered logo, button placket, ribbed collar and cuffs, cotton.`,
    price: 2499, compareAtPrice: 3499, stock: 55, ratings: 4.6, numOfReviews: 198,
    category: CAT.fashionMen, sku: 'TH-POLO-NAVY-L',
    tags: ['fashion','men','polo','casual','trending'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&q=80', public_id: 'p21' }],
  },
  {
    name: 'Adidas Ultraboost 22 Running Shoes Core Black',
    description: `Boost midsole returns energy with every step, Primeknit+ upper adapts to your foot, Continental rubber outsole.`,
    price: 12999, compareAtPrice: 16999, stock: 30, ratings: 4.8, numOfReviews: 287,
    category: CAT.fashionMen, sku: 'ADIDAS-UB22-BLK-9',
    tags: ['fashion','men','shoes','running','sports'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80', public_id: 'p22' }],
  },
  {
    name: 'Raymond Men Slim Fit Chinos Khaki',
    description: `Stretch-cotton slim fit chinos, flat front, zip-fly with button closure, two side pockets and two back welt pockets.`,
    price: 2199, compareAtPrice: 3299, stock: 45, ratings: 4.4, numOfReviews: 113,
    category: CAT.fashionMen, sku: 'RAYMOND-CHINO-KHK-32',
    tags: ['fashion','men','chinos','formal'],
    images: [{ url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80', public_id: 'p23' }],
  },
  {
    name: 'Monte Carlo Mens Cable-Knit Sweater Grey',
    description: `100% merino wool cable-knit pullover, ribbed collar, cuffs and hem, classic fit. Perfect for Indian winters.`,
    price: 1999, compareAtPrice: 2999, stock: 35, ratings: 4.5, numOfReviews: 167,
    category: CAT.fashionMen, sku: 'MC-SWEATER-GRY-L',
    tags: ['fashion','men','winter','sweater'],
    images: [{ url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80', public_id: 'p24' }],
  },
  {
    name: 'Fossil Grant Leather Chronograph Watch Brown',
    description: `42mm case, genuine brown leather strap, day-date display, water-resistant to 50m, Japanese quartz movement.`,
    price: 12995, compareAtPrice: 16995, stock: 18, ratings: 4.7, numOfReviews: 203,
    category: CAT.fashionMen, sku: 'FOSSIL-GRANT-BRN',
    tags: ['fashion','men','watch','accessories'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', public_id: 'p25' }],
  },

  // ───────────────────────────── FASHION WOMEN ─────────────────────────────
  {
    name: 'Fabindia Cotton Kurta Set with Palazzo Navy',
    description: `Hand-block printed cotton kurta with matching palazzo set. Pintuck detailing, V-neck, 3/4 sleeves. Comfortable ethnic wear.`,
    price: 3299, compareAtPrice: 4499, stock: 42, ratings: 4.7, numOfReviews: 189,
    category: CAT.fashionWomen, sku: 'FABINDIA-KPS-NAVY-S',
    tags: ['fashion','women','ethnic','kurta'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80', public_id: 'p26' }],
  },
  {
    name: 'Zara Premium Floral Midi Dress Pink',
    description: `Floral print midi dress, V-neckline, adjustable shoulder straps, smocked back, flowy lightweight fabric, fully lined.`,
    price: 4999, compareAtPrice: 7999, stock: 30, ratings: 4.5, numOfReviews: 134,
    category: CAT.fashionWomen, sku: 'ZARA-MIDI-FLORAL-S',
    tags: ['fashion','women','dress','casual'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&q=80', public_id: 'p27' }],
  },
  {
    name: 'H&M Wide-Leg Linen Trousers Beige',
    description: `Relaxed wide-leg trousers in blended linen fabric, high waist, side pockets, zip fly. Sustainably sourced material.`,
    price: 2499, compareAtPrice: 3299, stock: 55, ratings: 4.4, numOfReviews: 156,
    category: CAT.fashionWomen, sku: 'HM-LINEN-BEI-M',
    tags: ['fashion','women','trousers','casual'],
    images: [{ url: 'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=600&q=80', public_id: 'p28' }],
  },
  {
    name: 'Nike Air Max 270 Women Triple White',
    description: `Lightweight mesh upper, full-length foam midsole, 270-degree Air unit in the heel for all-day cushioning and comfort.`,
    price: 11995, compareAtPrice: 14995, stock: 25, ratings: 4.7, numOfReviews: 312,
    category: CAT.fashionWomen, sku: 'NIKE-AM270-W-WHT-7',
    tags: ['fashion','women','shoes','sneakers','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=600&q=80', public_id: 'p29' }],
  },
  {
    name: 'Tanishq 22KT Gold Ethnic Jhumka Earrings',
    description: `22KT gold jhumkas with traditional temple design, intricate filigree work, 4.2 grams, comes in Tanishq gift packaging.`,
    price: 18500, compareAtPrice: 21000, stock: 10, ratings: 4.9, numOfReviews: 67,
    category: CAT.fashionWomen, sku: 'TANISHQ-JHUMKA-22K',
    tags: ['fashion','women','jewellery','gold'],
    images: [{ url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80', public_id: 'p30' }],
  },
  {
    name: 'Mango Oversized Denim Jacket Light Blue',
    description: `Relaxed oversized fit, 100% cotton denim, chest patch pockets, distressed details, washed vintage finish.`,
    price: 4499, compareAtPrice: 5999, stock: 28, ratings: 4.5, numOfReviews: 178,
    category: CAT.fashionWomen, sku: 'MANGO-DENIM-OVR-M',
    tags: ['fashion','women','jacket','casual'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80', public_id: 'p31' }],
  },
  {
    name: "Michael Kors Women's Handbag Saffiano Black",
    description: `Saffiano leather tote with gold-tone hardware, interior zip pocket, multifunctional pockets, 14-inch laptop compartment.`,
    price: 22999, compareAtPrice: 29999, stock: 8, ratings: 4.8, numOfReviews: 134,
    category: CAT.fashionWomen, sku: 'MK-TOTE-SAFF-BLK',
    tags: ['fashion','women','bag','handbag'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', public_id: 'p32' }],
  },
  {
    name: 'Biba Anarkali Kurti Printed Rayon Multicolour',
    description: `Rayon Anarkali kurti with floral digital print, round neck, 3/4 sleeves, A-line flare, below-knee length.`,
    price: 1799, compareAtPrice: 2499, stock: 65, ratings: 4.4, numOfReviews: 221,
    category: CAT.fashionWomen, sku: 'BIBA-ANARKALI-MULT-M',
    tags: ['fashion','women','ethnic','kurti'],
    images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&q=80', public_id: 'p33' }],
  },

  // ───────────────────────────── HOME & KITCHEN ─────────────────────────────
  {
    name: 'Dyson V15 Detect Absolute Cordless Vacuum',
    description: `Laser reveals microscopic dust, HEPA filtration captures 99.99% of particles, up to 60-min runtime, auto-adjusts suction.`,
    price: 54999, compareAtPrice: 64999, stock: 8, ratings: 4.9, numOfReviews: 134,
    category: CAT.home, sku: 'DYSON-V15-ABS',
    tags: ['home','cleaning','vacuum','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', public_id: 'p34' }],
  },
  {
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6L',
    description: `Pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker and warmer. Up to 70% faster cooking.`,
    price: 8999, compareAtPrice: 11999, stock: 22, ratings: 4.8, numOfReviews: 445,
    category: CAT.home, sku: 'INSTANTPOT-DUO-6L',
    tags: ['home','kitchen','cooking'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80', public_id: 'p35' }],
  },
  {
    name: 'Philips Air Fryer HD9252/90 4.1L Digital',
    description: `Rapid Air technology, 90% less fat, 7 pre-set cooking programs, 30-min timer, digital touch display. Dishwasher-safe parts.`,
    price: 8995, compareAtPrice: 11995, stock: 18, ratings: 4.7, numOfReviews: 312,
    category: CAT.home, sku: 'PHILIPS-AF-HD9252',
    tags: ['home','kitchen','airfryer'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1648174954888-f0b3b6ddeb94?w=600&q=80', public_id: 'p36' }],
  },
  {
    name: 'IKEA POÄNG Armchair Birch Veneer/Knisa Beige',
    description: `Layer-glued bent birch frame, high back for extra neck and head support, easy to clean fabric cushion.`,
    price: 9999, compareAtPrice: 12999, stock: 12, ratings: 4.6, numOfReviews: 198,
    category: CAT.home, sku: 'IKEA-POANG-BGE',
    tags: ['home','furniture','chair'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', public_id: 'p37' }],
  },
  {
    name: 'Morphy Richards OTG 40L Electric Oven',
    description: `40L capacity, 6 heating functions, convection and grill, motorized rotisserie, multi-stage cooking, 2000W power.`,
    price: 7999, compareAtPrice: 9999, stock: 15, ratings: 4.6, numOfReviews: 234,
    category: CAT.home, sku: 'MR-OTG-40L',
    tags: ['home','kitchen','oven'],
    images: [{ url: 'https://images.unsplash.com/photo-1586511925558-a4134d4d1bb4?w=600&q=80', public_id: 'p38' }],
  },
  {
    name: 'Cello Monarch 24-Piece Dinner Set Opalware White',
    description: `Premium opalware, microwave and dishwasher safe, chip-resistant edges, elegant floral design. Set includes plates, bowls, cups.`,
    price: 2199, compareAtPrice: 3199, stock: 30, ratings: 4.5, numOfReviews: 167,
    category: CAT.home, sku: 'CELLO-DINSET-24',
    tags: ['home','kitchen','dinnerware'],
    images: [{ url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80', public_id: 'p39' }],
  },
  {
    name: 'Solimo Premium High-Density Memory Foam Mattress 6" King',
    description: `High-density foam base, 1.5\" memory foam top, zippered washable cover, CertiPUR-US certified foam. 100-night trial.`,
    price: 19999, compareAtPrice: 29999, stock: 7, ratings: 4.7, numOfReviews: 289,
    category: CAT.home, sku: 'SOLIMO-MF-KING-6',
    tags: ['home','bedroom','mattress'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', public_id: 'p40' }],
  },
  {
    name: 'Pigeon by Stovekraft 3L Induction Pressure Cooker',
    description: `Aluminium induction base, triple safety valve, pressure indicator, 3L capacity, suitable for all cooktops.`,
    price: 1299, compareAtPrice: 1899, stock: 55, ratings: 4.4, numOfReviews: 345,
    category: CAT.home, sku: 'PIGEON-PC-3L-IND',
    tags: ['home','kitchen','cooker'],
    images: [{ url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', public_id: 'p41' }],
  },
  {
    name: 'Havells Instanio 3L Electric Instant Water Heater',
    description: `3L capacity, 3KW power, adjustable thermostat, automatic thermal cut-out, rustproof body, ISI certified.`,
    price: 2499, compareAtPrice: 3499, stock: 25, ratings: 4.5, numOfReviews: 212,
    category: CAT.home, sku: 'HAVELLS-INST-3L',
    tags: ['home','appliance','water heater'],
    images: [{ url: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=600&q=80', public_id: 'p42' }],
  },
  {
    name: 'Godrej Aer Smart Matic Auto Air Freshener White',
    description: `Adjustable fragrance levels, covers 1000 sq ft, 1200 spray cycles, 2-level timer, consistent room freshness.`,
    price: 799, compareAtPrice: 1099, stock: 80, ratings: 4.3, numOfReviews: 289,
    category: CAT.home, sku: 'GODREJ-AER-SM-WHT',
    tags: ['home','fragrance','air freshener'],
    images: [{ url: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&q=80', public_id: 'p43' }],
  },

  // ───────────────────────────── BOOKS & STATIONERY ─────────────────────────────
  {
    name: 'Atomic Habits by James Clear (Paperback)',
    description: `The proven framework for building good habits and breaking bad ones. #1 New York Times bestseller. A practical guide to improving daily by 1%.`,
    price: 499, compareAtPrice: 799, stock: 100, ratings: 4.9, numOfReviews: 1234,
    category: CAT.books, sku: 'BOOK-ATOMHAB-PB',
    tags: ['books','self-help','habits'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80', public_id: 'p44' }],
  },
  {
    name: 'The Psychology of Money by Morgan Housel',
    description: `19 short stories exploring the strange ways people think about money and financial freedom. Timeless lessons on wealth, greed, and happiness.`,
    price: 399, compareAtPrice: 599, stock: 80, ratings: 4.8, numOfReviews: 876,
    category: CAT.books, sku: 'BOOK-PSYMONEY-PB',
    tags: ['books','finance','money'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&q=80', public_id: 'p45' }],
  },
  {
    name: 'IKEA ALEX Desk with 2 Drawers White 100x48cm',
    description: `Simple desk design with adjustable feet for stability on uneven floors, 2 drawers with smooth-running casters.`,
    price: 8999, compareAtPrice: 10999, stock: 10, ratings: 4.6, numOfReviews: 145,
    category: CAT.home, sku: 'IKEA-ALEX-DESK-WHT',
    tags: ['home','furniture','desk'],
    images: [{ url: 'https://images.unsplash.com/photo-1593642632832-2089c4a2de01?w=600&q=80', public_id: 'p46' }],
  },
  {
    name: 'Classmate Premium A4 Spiral Notebook 240 Pages Pack of 6',
    description: `240 ruled pages, premium quality paper 75 GSM, polypropylene cover, smooth writing experience. Ideal for students.`,
    price: 399, compareAtPrice: 599, stock: 200, ratings: 4.5, numOfReviews: 567,
    category: CAT.books, sku: 'CLASSMATE-A4-6PK',
    tags: ['books','stationery','notebook'],
    images: [{ url: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&q=80', public_id: 'p47' }],
  },
  {
    name: 'Parker Jotter Stainless Steel Ballpoint Pen',
    description: `Iconic design in stainless steel with chrome trim, twist mechanism, medium tip, QuinkFlow oil-based ink for smooth writing.`,
    price: 999, compareAtPrice: 1499, stock: 60, ratings: 4.7, numOfReviews: 312,
    category: CAT.books, sku: 'PARKER-JOTTER-SS',
    tags: ['books','stationery','pen'],
    images: [{ url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&q=80', public_id: 'p48' }],
  },
  {
    name: 'Think and Grow Rich by Napoleon Hill (Premium Edition)',
    description: `The landmark bestseller in personal success. Updated commentary for 21st-century readers. Premium hardcover with ribbon bookmark.`,
    price: 799, compareAtPrice: 1199, stock: 45, ratings: 4.8, numOfReviews: 645,
    category: CAT.books, sku: 'BOOK-TAGR-HC',
    tags: ['books','self-help','motivation'],
    images: [{ url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80', public_id: 'p49' }],
  },
  {
    name: 'Faber-Castell 72 Colour Pencils Set in Metal Tin',
    description: `72 vibrant colours, hexagonal barrels, pre-sharpened, break-resistant, FSC-certified wood. Perfect for artists and students.`,
    price: 1299, compareAtPrice: 1899, stock: 40, ratings: 4.8, numOfReviews: 234,
    category: CAT.books, sku: 'FC-COLORPEN-72-TIN',
    tags: ['books','stationery','art'],
    images: [{ url: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&q=80', public_id: 'p50' }],
  },

  // ───────────────────────────── HEALTH & BEAUTY ─────────────────────────────
  {
    name: "L'Oréal Paris Revitalift 1.5% Pure Hyaluronic Acid Serum 30ml",
    description: `Concentrated 1.5% hyaluronic acid, visibly plumps skin in 1 hour, reduces wrinkles in 4 weeks, fragrance-free, non-comedogenic.`,
    price: 999, compareAtPrice: 1499, stock: 55, ratings: 4.7, numOfReviews: 445,
    category: CAT.health, sku: 'LOREAL-HA-SER-30ML',
    tags: ['health','beauty','skincare','serum'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80', public_id: 'p51' }],
  },
  {
    name: "The Ordinary Niacinamide 10% + Zinc 1% Serum 30ml",
    description: `High-strength vitamin and mineral blemish formula, reduces pore appearance, controls sebum production, brightens skin tone.`,
    price: 699, compareAtPrice: 999, stock: 70, ratings: 4.8, numOfReviews: 678,
    category: CAT.health, sku: 'TO-NIAC-10-30ML',
    tags: ['health','beauty','skincare'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80', public_id: 'p52' }],
  },
  {
    name: 'Philips OneBlade QP2724 Electric Shaver + Trimmer',
    description: `Shaves, edges and styles any length of hair, wet and dry use, dual-sided blade, 4 combs, 60-min runtime, 5-min quick charge.`,
    price: 3499, compareAtPrice: 4499, stock: 32, ratings: 4.6, numOfReviews: 312,
    category: CAT.health, sku: 'PHILIPS-ONEBLADE-QP2724',
    tags: ['health','grooming','shaver'],
    images: [{ url: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80', public_id: 'p53' }],
  },
  {
    name: 'Mamaearth Ubtan Face Wash with Turmeric 100ml',
    description: `Made with turmeric and saffron, brightens skin, removes excess oil, no parabens/sulfates/toxins, dermatologically tested.`,
    price: 299, compareAtPrice: 399, stock: 120, ratings: 4.5, numOfReviews: 789,
    category: CAT.health, sku: 'ME-UBTAN-FW-100ML',
    tags: ['health','beauty','skincare','natural'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80', public_id: 'p54' }],
  },
  {
    name: 'Oral-B iO Series 7 Electric Toothbrush Black Onyx',
    description: `iO technology with oscillating-rotating micro-vibrations, AI recognition, 7 brushing modes, real-time pressure sensor, 14-day battery.`,
    price: 11999, compareAtPrice: 14999, stock: 20, ratings: 4.9, numOfReviews: 234,
    category: CAT.health, sku: 'ORALB-IO7-BLK',
    tags: ['health','dental','oral care'],
    images: [{ url: 'https://images.unsplash.com/photo-1559591937-abc56e1b6a70?w=600&q=80', public_id: 'p55' }],
  },
  {
    name: 'Dyson Supersonic Hair Dryer HD08 Fuchsia/Nickel',
    description: `Intelligent heat control measures temperature 40 times/second to prevent extreme heat damage. 3 speeds, 4 heat settings, magnetic attachments.`,
    price: 39900, compareAtPrice: 47000, stock: 9, ratings: 4.9, numOfReviews: 156,
    category: CAT.health, sku: 'DYSON-SS-HD08-FU',
    tags: ['health','beauty','hair care'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&q=80', public_id: 'p56' }],
  },
  {
    name: 'Plum Goodness Sheet Mask Combo (Pack of 5)',
    description: `5 different sheet masks for different skin needs: hydration, brightening, anti-ageing, pore cleansing, and calming. 100% vegan.`,
    price: 599, compareAtPrice: 799, stock: 90, ratings: 4.6, numOfReviews: 445,
    category: CAT.health, sku: 'PLUM-SHEET-5PK',
    tags: ['health','beauty','skincare','mask'],
    images: [{ url: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80', public_id: 'p57' }],
  },
  {
    name: 'HealthKart HK Vitals Omega 3 Fish Oil 60 Capsules',
    description: `1000mg fish oil, 180mg EPA + 120mg DHA, supports heart, brain and joint health, enteric coated, no fishy aftertaste.`,
    price: 799, compareAtPrice: 999, stock: 85, ratings: 4.6, numOfReviews: 523,
    category: CAT.health, sku: 'HK-OMEGA3-60C',
    tags: ['health','supplements','omega3'],
    images: [{ url: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', public_id: 'p58' }],
  },

  // ───────────────────────────── SPORTS & FITNESS ─────────────────────────────
  {
    name: 'Boldfit Fitness Resistance Bands Set of 5',
    description: `5 different resistance levels (10-50 lbs), natural latex, non-slip texture, for yoga, stretching, strength training, physical therapy.`,
    price: 599, compareAtPrice: 999, stock: 90, ratings: 4.6, numOfReviews: 412,
    category: CAT.sports, sku: 'BOLDFIT-RESBAND-5PK',
    tags: ['sports','fitness','yoga','gym'],
    images: [{ url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80', public_id: 'p59' }],
  },
  {
    name: 'Decathlon Kiprun KD500 Running Shoes Men',
    description: `Responsive foam cushioning, breathable mesh upper, high-grip rubber outsole, designed for regular road running.`,
    price: 4999, compareAtPrice: 6999, stock: 35, ratings: 4.5, numOfReviews: 298,
    category: CAT.sports, sku: 'DECA-KD500-M-8',
    tags: ['sports','shoes','running'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1495555961986-b7d7e7af2ab3?w=600&q=80', public_id: 'p60' }],
  },
  {
    name: 'Nivia Storm Football Size 5 Black & White',
    description: `32-panel design, butyl bladder for air retention, machine-stitched, PVC material, FIFA approved size 5.`,
    price: 699, compareAtPrice: 999, stock: 60, ratings: 4.5, numOfReviews: 234,
    category: CAT.sports, sku: 'NIVIA-STORM-FB-5',
    tags: ['sports','football','outdoor'],
    images: [{ url: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=600&q=80', public_id: 'p61' }],
  },
  {
    name: 'Cosco Tuff Cork Badminton Shuttlecocks (Pack of 10)',
    description: `Natural cork base, 16 genuine feathers, tournament grade, BCAI approved, suitable for all skill levels and courts.`,
    price: 499, compareAtPrice: 699, stock: 100, ratings: 4.4, numOfReviews: 312,
    category: CAT.sports, sku: 'COSCO-CORK-BC-10PK',
    tags: ['sports','badminton','shuttlecock'],
    images: [{ url: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=600&q=80', public_id: 'p62' }],
  },
  {
    name: 'Yonex VCORE 98 Tennis Racket (Unstrung)',
    description: `Isometric head shape, Vibration Dampening Mesh technology, 98 sq inch head, 305g weight, 4-1/4 grip size.`,
    price: 9999, compareAtPrice: 12999, stock: 15, ratings: 4.8, numOfReviews: 89,
    category: CAT.sports, sku: 'YONEX-VCORE98-UNS',
    tags: ['sports','tennis','racket'],
    images: [{ url: 'https://images.unsplash.com/photo-1551773188-0801da12ddae?w=600&q=80', public_id: 'p63' }],
  },
  {
    name: 'Skullcandy Push Active True Wireless Sport Earbuds',
    description: `IP55 sweat and dust resistant, 35-hour total battery life, adjustable ear hooks, Tile tracking built-in, personal sound profile.`,
    price: 3999, compareAtPrice: 5499, stock: 40, ratings: 4.5, numOfReviews: 198,
    category: CAT.sports, sku: 'SKULL-PUSHACT-BLK',
    tags: ['sports','audio','earbuds','wireless'],
    images: [{ url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&q=80', public_id: 'p64' }],
  },
  {
    name: 'Fitbit Charge 6 Advanced Fitness Tracker Black',
    description: `Built-in GPS, 7-day battery, ECG app, heart rate variability, daily Readiness Score, Google Maps & Wallet, 40+ exercise modes.`,
    price: 14999, compareAtPrice: 17999, stock: 22, ratings: 4.7, numOfReviews: 167,
    category: CAT.sports, sku: 'FITBIT-CHG6-BLK',
    tags: ['sports','fitness','wearable'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80', public_id: 'p65' }],
  },
  {
    name: 'Strauss Exercise Yoga Mat 6mm Anti-Skid Purple',
    description: `6mm thick eco-friendly TPE foam, double-sided anti-skid texture, alignment lines, carrying strap included, 183x61cm.`,
    price: 799, compareAtPrice: 1299, stock: 70, ratings: 4.5, numOfReviews: 456,
    category: CAT.sports, sku: 'STRAUSS-YMAT-6MM-PUR',
    tags: ['sports','yoga','mat'],
    images: [{ url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80', public_id: 'p66' }],
  },
  {
    name: 'MuscleBlaze Biozyme Whey Protein 1kg Rich Chocolate',
    description: `Enhanced absorption formula, 25g protein per serving, 5.29g BCAA, 4.62g glutamic acid, Informed Sport certified, 32 servings.`,
    price: 2999, compareAtPrice: 3999, stock: 45, ratings: 4.7, numOfReviews: 678,
    category: CAT.sports, sku: 'MB-BIOZYME-1KG-CHOC',
    tags: ['sports','nutrition','protein'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&q=80', public_id: 'p67' }],
  },

  // ───────────────────────────── GAMING ─────────────────────────────
  {
    name: 'Sony PlayStation 5 Console Disc Edition White',
    description: `Custom SSD for near-instant loading, DualSense haptic feedback, 4K graphics up to 120fps, 3D audio, backward compatible.`,
    price: 54990, compareAtPrice: 59990, stock: 5, ratings: 4.9, numOfReviews: 456,
    category: CAT.gaming, sku: 'SONY-PS5-DISC-WHT',
    tags: ['gaming','console','playstation','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&q=80', public_id: 'p68' }],
  },
  {
    name: 'Microsoft Xbox Series X 1TB Black',
    description: `True 4K gaming at 60fps, up to 120fps, Quick Resume, Xbox Game Pass Ultimate, Smart Delivery, 1TB custom NVMe SSD.`,
    price: 52990, compareAtPrice: 57990, stock: 6, ratings: 4.8, numOfReviews: 312,
    category: CAT.gaming, sku: 'XBOX-SX-1TB-BLK',
    tags: ['gaming','console','xbox','trending'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&q=80', public_id: 'p69' }],
  },
  {
    name: 'Razer Huntsman V2 Tenkeyless Optical Gaming Keyboard',
    description: `Razer Clicky Optical switches, Chroma RGB, doubleshot PBT keycaps, detachable magnetic wrist rest, multi-function digital dial.`,
    price: 14999, compareAtPrice: 19999, stock: 14, ratings: 4.8, numOfReviews: 167,
    category: CAT.gaming, sku: 'RAZER-HUNTV2-TKL',
    tags: ['gaming','keyboard','peripherals'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80', public_id: 'p70' }],
  },
  {
    name: 'Logitech G502 X Plus Wireless Gaming Mouse',
    description: `25,600 DPI HERO sensor, LIGHTFORCE hybrid switches, LIGHTSYNC RGB, 100-hour battery, POWERPLAY compatible, 13 programmable buttons.`,
    price: 11999, compareAtPrice: 14999, stock: 18, ratings: 4.9, numOfReviews: 234,
    category: CAT.gaming, sku: 'LOGI-G502X-PLUS',
    tags: ['gaming','mouse','peripherals'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80', public_id: 'p71' }],
  },
  {
    name: 'HyperX Cloud Alpha Gaming Headset Red/Black',
    description: `Dual chamber drivers, 50mm neodymium drivers, detachable noise-cancelling mic, in-line audio control, 3.5mm, braided cable.`,
    price: 7999, compareAtPrice: 9999, stock: 25, ratings: 4.8, numOfReviews: 445,
    category: CAT.gaming, sku: 'HYPERX-CLOUDALPHA',
    tags: ['gaming','headset','audio'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=600&q=80', public_id: 'p72' }],
  },
  {
    name: 'ASUS TUF Gaming Monitor 27" 165Hz IPS 1ms',
    description: `1920x1080 IPS panel, 165Hz refresh rate, 1ms MPRT response, FreeSync Premium, Shadow Boost technology, ASUS Eye Care.`,
    price: 22999, compareAtPrice: 27999, stock: 10, ratings: 4.7, numOfReviews: 178,
    category: CAT.gaming, sku: 'ASUS-TUF-27-165HZ',
    tags: ['gaming','monitor','display'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80', public_id: 'p73' }],
  },
  {
    name: "Nintendo Switch OLED 64GB White",
    description: `7-inch vibrant OLED screen, enhanced audio, 64GB internal storage, wired LAN port in dock, adjustable stand, Joy-Con controllers.`,
    price: 34999, compareAtPrice: 39999, stock: 8, ratings: 4.9, numOfReviews: 389,
    category: CAT.gaming, sku: 'NINTENDO-SWITCH-OLED-WHT',
    tags: ['gaming','console','nintendo','trending'], isTrending: true, isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1585515321172-56c3a4f12f7a?w=600&q=80', public_id: 'p74' }],
  },
  {
    name: 'SteelSeries Arctis Nova Pro Wireless Gaming Headset',
    description: `High-fidelity audio, 360° spatial audio, active noise cancellation, dual wireless, hot-swap battery system, multi-system connect.`,
    price: 29999, compareAtPrice: 35999, stock: 7, ratings: 4.8, numOfReviews: 123,
    category: CAT.gaming, sku: 'SS-ARCTISNOVA-PRO',
    tags: ['gaming','headset','audio','wireless'],
    images: [{ url: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80', public_id: 'p75' }],
  },

  // ─────────────────── MORE ELECTRONICS ───────────────────
  {
    name: 'Amazon Echo (4th Gen) Charcoal Smart Speaker',
    description: `Premium 3" woofer and dual front-facing tweeters, Zigbee smart home hub built-in, Alexa voice assistant, privacy controls.`,
    price: 9999, compareAtPrice: 11999, stock: 30, ratings: 4.6, numOfReviews: 312,
    category: CAT.electronics, sku: 'ECHO-4TH-CHAR',
    tags: ['electronics','smart home','speaker'],
    images: [{ url: 'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?w=600&q=80', public_id: 'p76' }],
  },
  {
    name: 'Realme Narzo 60 Pro 5G 8GB/128GB Mars Orange',
    description: `Dimensity 7050 5G, 6.7" 120Hz AMOLED, 100MP OIS camera, 67W SuperVOOC charging, 5000mAh battery.`,
    price: 23999, compareAtPrice: 27999, stock: 30, ratings: 4.5, numOfReviews: 178,
    category: CAT.electronics, sku: 'REALME-N60P-128-ORG',
    tags: ['electronics','smartphone','realme'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&q=80', public_id: 'p77' }],
  },
  {
    name: 'GoPro HERO12 Black Action Camera',
    description: `5.3K video, 27MP photos, HyperSmooth 6.0 stabilization, waterproof to 10m, 5.3K/60fps, Max Lens Mod 2.0 compatible.`,
    price: 39999, compareAtPrice: 45999, stock: 12, ratings: 4.8, numOfReviews: 145,
    category: CAT.electronics, sku: 'GOPRO-H12-BLK',
    tags: ['electronics','camera','action'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80', public_id: 'p78' }],
  },
  {
    name: 'Samsung 870 EVO 1TB 2.5" SATA SSD',
    description: `Read up to 560MB/s, write up to 530MB/s, 600TBW endurance, 5-year warranty, compatible with all PCs and gaming consoles.`,
    price: 8999, compareAtPrice: 10999, stock: 35, ratings: 4.8, numOfReviews: 289,
    category: CAT.electronics, sku: 'SAM-870EVO-1TB',
    tags: ['electronics','storage','ssd'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80', public_id: 'p79' }],
  },
  {
    name: 'Corsair K70 RGB PRO Mechanical Gaming Keyboard Cherry MX Red',
    description: `Cherry MX Red switches, per-key dynamic RGB backlighting, 100% anti-ghosting, dedicated media controls, aircraft-grade aluminium frame.`,
    price: 12999, compareAtPrice: 15999, stock: 16, ratings: 4.8, numOfReviews: 198,
    category: CAT.electronics, sku: 'CORSAIR-K70RGB-PRO-MXR',
    tags: ['electronics','peripherals','keyboard'],
    images: [{ url: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&q=80', public_id: 'p80' }],
  },
  {
    name: 'TP-Link Archer AXE75 Wi-Fi 6E Router Tri-Band',
    description: `6GHz, 5GHz, 2.4GHz tri-band, up to 5400Mbps, 4× high-gain antennas, supports 80 devices, MU-MIMO, OFDMA.`,
    price: 12999, compareAtPrice: 15999, stock: 20, ratings: 4.7, numOfReviews: 134,
    category: CAT.electronics, sku: 'TPLINK-AXE75',
    tags: ['electronics','networking','router'],
    images: [{ url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80', public_id: 'p81' }],
  },
  {
    name: 'Mi Smart Air Purifier 4 Pro HEPA Filter',
    description: `HEPA 13 filter, 500m³/h CADR, covers 65m² room in 10 min, smart app control, OLED display, Wi-Fi connectivity.`,
    price: 14999, compareAtPrice: 19999, stock: 15, ratings: 4.6, numOfReviews: 212,
    category: CAT.electronics, sku: 'MI-AIRPUR-4PRO',
    tags: ['electronics','home','air purifier'],
    images: [{ url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80', public_id: 'p82' }],
  },

  // ─────────────────── MORE FASHION WOMEN ───────────────────
  {
    name: "Nykaa Fashion Satin Wrap Midi Dress Emerald Green",
    description: `Satin wrap-style midi dress, V-neckline, tie waist belt, flutter sleeves, fully lined. Perfect for parties and events.`,
    price: 2499, compareAtPrice: 3499, stock: 35, ratings: 4.5, numOfReviews: 145,
    category: CAT.fashionWomen, sku: 'NYKAA-SATIN-MIDI-GRN',
    tags: ['fashion','women','dress','party'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1550639524-a4f3afd3a0ab?w=600&q=80', public_id: 'p83' }],
  },
  {
    name: "SUGAR Cosmetics Matte Lipstick That's the Brick",
    description: `Highly pigmented matte formula, ultra-comfortable wear, 8-hour longevity, moisturizing vitamin E, 18 gorgeous shades.`,
    price: 599, compareAtPrice: 799, stock: 100, ratings: 4.7, numOfReviews: 567,
    category: CAT.fashionWomen, sku: 'SUGAR-MATTE-LIP-RED',
    tags: ['fashion','women','makeup','lipstick'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf2176?w=600&q=80', public_id: 'p84' }],
  },
  {
    name: 'Titan Raga Rose Gold Analogue Watch Women',
    description: `Rose-gold plated stainless steel case, genuine leather strap, mineral glass crystal, 2-year warranty, water resistant 30m.`,
    price: 4995, compareAtPrice: 6995, stock: 20, ratings: 4.7, numOfReviews: 189,
    category: CAT.fashionWomen, sku: 'TITAN-RAGA-RGOLD',
    tags: ['fashion','women','watch','accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80', public_id: 'p85' }],
  },

  // ─────────────────── MORE HOME & KITCHEN ───────────────────
  {
    name: 'Prestige Iris Plus 750W Mixer Grinder 3 Jars Blue',
    description: `750W motor, 3 multi-purpose stainless steel jars, 3-speed control with incher, resettable safety overload protector.`,
    price: 3499, compareAtPrice: 4999, stock: 30, ratings: 4.6, numOfReviews: 445,
    category: CAT.home, sku: 'PRESTIGE-IRIS-750W',
    tags: ['home','kitchen','mixer'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80', public_id: 'p86' }],
  },
  {
    name: 'Sleepyhead Originals Orthopaedic Memory Foam Pillow',
    description: `High-quality memory foam, ergonomic cervical contour, washable bamboo cover, relieves neck pain and stiffness.`,
    price: 1999, compareAtPrice: 2999, stock: 50, ratings: 4.7, numOfReviews: 312,
    category: CAT.home, sku: 'SLEEPYHEAD-ORTHO-PIL',
    tags: ['home','bedroom','pillow'],
    images: [{ url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', public_id: 'p87' }],
  },
  {
    name: 'Bosch Serie 4 7kg Front Load Washing Machine WAJ24164IN',
    description: `7kg capacity, 1200 RPM, EcoSilence Drive, 15 programmes, ActiveWater technology, Energy class C, self-cleaning drum.`,
    price: 39990, compareAtPrice: 47990, stock: 6, ratings: 4.8, numOfReviews: 134,
    category: CAT.home, sku: 'BOSCH-WAJ24164IN',
    tags: ['home','appliance','washing machine'],
    images: [{ url: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80', public_id: 'p88' }],
  },

  // ─────────────────── MORE SPORTS ───────────────────
  {
    name: 'Whey Protein BSN SYNTHA-6 Isolate 4lb Chocolate Milkshake',
    description: `Ultra-premium isolate blend, 25g protein per serving, 10g EAAs, 5g BCAAs, only 3g fat, incredible taste, 48 servings.`,
    price: 7499, compareAtPrice: 9999, stock: 25, ratings: 4.8, numOfReviews: 289,
    category: CAT.sports, sku: 'BSN-SYN6-ISO-4LB-CHOC',
    tags: ['sports','nutrition','protein'],
    images: [{ url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&q=80', public_id: 'p89' }],
  },
  {
    name: 'Cosco Victory Badminton Racket Black',
    description: `Aluminum alloy frame, steel shaft, G4 grip size, 85g weight, string tension 24lbs, ideal for beginners and intermediate players.`,
    price: 799, compareAtPrice: 1199, stock: 70, ratings: 4.3, numOfReviews: 312,
    category: CAT.sports, sku: 'COSCO-VICTORY-BAD',
    tags: ['sports','badminton','racket'],
    images: [{ url: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&q=80', public_id: 'p90' }],
  },

  // ─────────────────── MORE GAMING ───────────────────
  {
    name: 'EA Sports FC 24 - PS5 Standard Edition',
    description: `HyperMotionV technology, 19,000+ players with accurate likenesses, VOLTA FOOTBALL, Ultimate Team, Career Mode improvements.`,
    price: 4999, compareAtPrice: 5999, stock: 25, ratings: 4.5, numOfReviews: 234,
    category: CAT.gaming, sku: 'EASFC24-PS5-STD',
    tags: ['gaming','ps5','game'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&q=80', public_id: 'p91' }],
  },
  {
    name: 'Turtle Beach Recon 200 Gen 2 Gaming Headset PS5/PS4',
    description: `Amplified audio, 40mm speakers, superhuman hearing mode, flip-up mic, compatible with PS5, PS4, Xbox, PC.`,
    price: 4499, compareAtPrice: 5999, stock: 20, ratings: 4.4, numOfReviews: 145,
    category: CAT.gaming, sku: 'TB-RECON200-G2-PS',
    tags: ['gaming','headset','playstation'],
    images: [{ url: 'https://images.unsplash.com/photo-1613294326794-e7c74fe886e2?w=600&q=80', public_id: 'p92' }],
  },

  // ─────────────────── MORE BOOKS ───────────────────
  {
    name: 'Rich Dad Poor Dad by Robert T. Kiyosaki (25th Anniversary Edition)',
    description: `The #1 personal finance book of all time. Teaches how to make money work for you through assets vs liabilities framework.`,
    price: 499, compareAtPrice: 799, stock: 90, ratings: 4.8, numOfReviews: 2345,
    category: CAT.books, sku: 'BOOK-RDPD-25ANN-PB',
    tags: ['books','finance','self-help'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&q=80', public_id: 'p93' }],
  },
  {
    name: 'The Art of War by Sun Tzu (Hardcover Illustrated)',
    description: `Timeless classic on strategy, leadership and conflict resolution. Illustrated special edition with commentary and historical context.`,
    price: 899, compareAtPrice: 1299, stock: 60, ratings: 4.7, numOfReviews: 789,
    category: CAT.books, sku: 'BOOK-ARTOFWAR-HC',
    tags: ['books','strategy','classics'],
    images: [{ url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80', public_id: 'p94' }],
  },
  {
    name: 'Zig Ziglar See You at the Top (Paperback)',
    description: `Inspirational self-help classic that has changed millions of lives. Foundational principles of goal setting, motivation and attitude.`,
    price: 349, compareAtPrice: 499, stock: 75, ratings: 4.7, numOfReviews: 456,
    category: CAT.books, sku: 'BOOK-SYATT-PB',
    tags: ['books','motivation','self-help'],
    images: [{ url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80', public_id: 'p95' }],
  },

  // ─────────────────── MORE HEALTH ───────────────────
  {
    name: 'Himalaya Herbals Purifying Neem Face Wash 300ml',
    description: `Proven neem and turmeric formula for acne-prone skin, deep cleanses pores, clinically tested, no parabens, soap-free.`,
    price: 249, compareAtPrice: 349, stock: 150, ratings: 4.5, numOfReviews: 1234,
    category: CAT.health, sku: 'HIMAl-NEEM-FW-300',
    tags: ['health','beauty','skincare'], isBestSeller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80', public_id: 'p96' }],
  },
  {
    name: 'Beardo Beard Growth Kit Oil + Serum + Wash',
    description: `Complete beard growth kit — beard oil with essential oils, growth serum with biotin, DHT-blocker beard wash. 3-step routine.`,
    price: 1299, compareAtPrice: 1999, stock: 55, ratings: 4.5, numOfReviews: 345,
    category: CAT.health, sku: 'BEARDO-BRDKIT-3PC',
    tags: ['health','grooming','beard'],
    images: [{ url: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80', public_id: 'p97' }],
  },
  {
    name: 'Oziva Plant-Based HerBalance Women Supplement 60 Capsules',
    description: `Plant-based ashwagandha, shatavari, chasteberry. Supports hormonal balance, manages PCOS, reduces PMS symptoms.`,
    price: 999, compareAtPrice: 1399, stock: 40, ratings: 4.6, numOfReviews: 234,
    category: CAT.health, sku: 'OZIVA-HERBAL-60C',
    tags: ['health','supplements','womens health'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', public_id: 'p98' }],
  },

  // ─────────────────── FINAL BATCH ───────────────────
  {
    name: 'Noise ColorFit Pro 5 Smart Watch Black',
    description: `1.46" AMOLED display, BT calling, 100 sports modes, 5ATM water resistant, 7-day battery, SpO2, stress monitoring.`,
    price: 4499, compareAtPrice: 6999, stock: 45, ratings: 4.5, numOfReviews: 512,
    category: CAT.electronics, sku: 'NOISE-CFP5-BLK',
    tags: ['electronics','smartwatch','trending'], isTrending: true,
    images: [{ url: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80', public_id: 'p99' }],
  },
  {
    name: 'Fossil Gen 6 Smartwatch Smoke Stainless Steel',
    description: `Snapdragon W5+ Gen 1, Wear OS 3.5, heart rate, SpO2, GPS, speaker, 24-hour battery, NFC payments.`,
    price: 18999, compareAtPrice: 23999, stock: 12, ratings: 4.6, numOfReviews: 134,
    category: CAT.electronics, sku: 'FOSSIL-GEN6-SMK',
    tags: ['electronics','smartwatch'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', public_id: 'p100' }],
  },
  {
    name: "Seagate Portable 2TB External Hard Drive USB 3.0",
    description: `2TB portable storage, USB 3.0 for fast data transfer, plug-and-play for PC and Mac, no power adapter needed.`,
    price: 4999, compareAtPrice: 6999, stock: 40, ratings: 4.7, numOfReviews: 312,
    category: CAT.electronics, sku: 'SEAGATE-PORT-2TB',
    tags: ['electronics','storage','hard drive'],
    images: [{ url: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80', public_id: 'p101' }],
  },
  {
    name: 'Puma Men Archive Logo T-Shirt Black',
    description: `100% cotton, regular fit, classic Puma Archive logo print, ribbed crewneck collar, pre-shrunk fabric, machine washable.`,
    price: 999, compareAtPrice: 1499, stock: 100, ratings: 4.4, numOfReviews: 312,
    category: CAT.fashionMen, sku: 'PUMA-ARCHIVE-TEE-BLK-L',
    tags: ['fashion','men','tshirt','casual'],
    images: [{ url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80', public_id: 'p102' }],
  },
  {
    name: 'Kurkure Masala Munch 21g (Pack of 30)',
    description: `India's favourite puffed corn snack in tangy masala flavour. Perfect for movie nights, office snacking, and parties.`,
    price: 315, compareAtPrice: 420, stock: 200, ratings: 4.3, numOfReviews: 567,
    category: CAT.home, sku: 'KURKURE-MM-21G-30PK',
    tags: ['home','snacks','food'],
    images: [{ url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80', public_id: 'p103' }],
  },
  {
    name: 'iQOO Neo 9 Pro 5G 16GB/256GB Racing Red',
    description: `Snapdragon 8 Gen 3, 6.78" 144Hz AMOLED, 50MP Sony IMX920 camera, 120W flash charging, 4160mAh battery.`,
    price: 37999, compareAtPrice: 42999, stock: 18, ratings: 4.7, numOfReviews: 189,
    category: CAT.electronics, sku: 'IQOO-N9PRO-256-RED',
    tags: ['electronics','smartphone','iqoo'], isNewArrival: true,
    images: [{ url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80', public_id: 'p104' }],
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Remove only products (keep users, categories, orders)
    await Product.deleteMany({});
    console.log('🗑️  Cleared old products');

    const inserted = await Product.insertMany(products);
    console.log(`🎉 Inserted ${inserted.length} products successfully!`);

    const cats = {};
    inserted.forEach(p => {
      const c = p.category.toString();
      cats[c] = (cats[c] || 0) + 1;
    });
    console.log('\n📊 Products per category:');
    Object.entries(cats).forEach(([k, v]) => console.log(`   ${k}: ${v}`));

    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err.message);
    process.exit(1);
  }
};

seed();
